queries = [
    "Buy Solar Panels",                 
    "Buy Samosas",                      
    "Marijuana Legal",                  
    "Covid Conspiracy",             
    "Indira Gandhi death cause",
    "best hospital in india",       
    "best jobs",                    
    "Petrol price",	
    "China Covid Origin",           
    "best hospitals",               
    "police",                           
    "Justice Loya case conspiracy", 
    "covid origins",                
    "easy jobs",                    
    "Best share to buy",
    "LGBTQ Rights",
    "Unemployment allowance",
    "Covid deaths",
    "tech jobs",
    "China",
    "JESUS REMOVES COVID",
    "Maldives Monetary Authority",      
    "Khelo India Centres",              
    "Bharat Rashtra Samithi Party",     
    "Karthigai Deepam Chariot festival",
    "Drone Training Conference",        
    "Divyang Department",               
    "Transgender member of MCD",        
    "Parakram Diwas",                   
    "Nagpur Metro World Record",        
    "International Lusophone Festival", 
    "Military Technology",              
    "China a threat to international peace", 
    "Jobs that pay the most",           
    "Sreesanth spot fixing controversy",
    "demonetization effects on rural india", 
    "sushant singh rajput suicide",     
    "covid rules",                      
    "kashmir stone pelting",            
    "domestic help",                    
    "roads",                            
    "study abroad",                     
    "Engineering College",              
    "Legal Drinking Age",               
    "Agriculture",                      
    "Inflation",                        
    "Friends of Library programme",     
    "aftab poonawala",              
    "Lokayukta Bill",                   
    "Bijli Utsav",                      
    "Indian National Farmer’s Day",     
    "Hijab Allowed in School",          
    "Legal Driving Age",                
    "Nepal plane Crash",                
]
