base_city = "New Delhi,Delhi,India"

cities = [
    # base_city,
    #"Amritsar,Punjab,India",
    #"Kurukshetra,Haryana,India",
    #"Korba,Chhattisgarh,India",
    #"New Delhi,Delhi,India", #will stay commented if same as base city
    #"Lucknow,Uttar Pradesh,India",
    #"Agra,Uttar Pradesh,India",
    #"Jhansi,Uttar Pradesh,India",
    #"Patna,Bihar,India",
    # "Guwahati,Assam,India",
    #"Dibrugarh,Assam,India",
    # "Shillong,Meghalaya,India",
    # "Ahmedabad,Gujarat,India",
    # "Bhopal,Madhya Pradesh,India",
    # "Nagpur,Maharashtra,India",
    # "Mumbai,Maharashtra,India",
    # "Pune,Maharashtra,India",
    #"Jamshedpur,Jharkhand,India",
    # "Kharagpur,West Bengal,India",
    #"Kolkata,West Bengal,India",
    # "Shivamogga,Karnataka,India",
    #"Bengaluru,Karnataka,India",
    # "Bhubaneswar,Odisha,India",
    # "Hyderabad,Telangana,India",
    # "Visakhapatnam,Andhra Pradesh,India",
    #"Sivakasi,Tamil Nadu,India",
    # "Chennai,Tamil Nadu,India",
    # "Kochi,Kerala,India",

    #Following are all the capital cities of states of India
    base_city,
    "522237,Andhra Pradesh,India",
    "Srinagar,Jammu and Kashmir,India",
    "Ladakh,India",
    "Amritsar,Punjab,India",
    "Arunachal Pradesh,India",
    "Assam,India",
    "Patna,Bihar,India",
    "Raipur,Chhattisgarh,India",
    "Panaji,Goa,India",
    "Gandhinagar,Gujarat,India",
    "Faridabad,Haryana,India",
    "Shimla,Himachal Pradesh,India",
    "Ranchi,Jharkhand,India",
    "Bengaluru,Karnataka,India",
    "Thiruvananthapuram,Kerala,India",
    "Bhopal,Madhya Pradesh,India",
    "Mumbai,Maharashtra,India",
    "Imphal,Manipur,India",
    "Shillong,Meghalaya,India",
    "Aizawl,Mizoram,India",
    "Kohima,Nagaland,India",
    "Bhubaneswar,Odisha,India",
    "Jaipur,Rajasthan,India",
    "Gangtok,Sikkim,India",
    "Chennai,Tamil Nadu,India",
    "Hyderabad,Telangana,India",
    "Agartala,Tripura,India",
    "Lucknow,Uttar Pradesh,India",
    "Dehradun ,Uttarakhand,India",
    "Kolkata,West Bengal,India",
]